// <auto-generated />
using System;
using Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Infrastructure.Migrations
{
    [DbContext(typeof(DbDocGenContext))]
    [Migration("20260519022310_StudentDetailsPageSupport")]
    partial class StudentDetailsPageSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diploma")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DiplomaExaminationCommissionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProtocolRange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalPages")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaExaminationCommissionId")
                        .IsUnique();

                    b.ToTable("Archives", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.Defence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DefenceDate")
                        .HasColumnType("date");

                    b.Property<int?>("DiplomaExaminationCommissionId")
                        .HasColumnType("integer");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("QualificationWorkId")
                        .HasColumnType("integer");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaExaminationCommissionId");

                    b.HasIndex("QualificationWorkId")
                        .IsUnique();

                    b.ToTable("Defences", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.QualificationWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionScore")
                        .HasColumnType("integer");

                    b.Property<string>("EctsGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasDiplomaWithHonors")
                        .HasColumnType("boolean");

                    b.Property<string>("NationalGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagesCount")
                        .HasColumnType("integer");

                    b.Property<float>("PlagiarismPercent")
                        .HasColumnType("real");

                    b.Property<string>("PracticeBase")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewerScore")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SupervisorScore")
                        .HasColumnType("integer");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("UniquePercent")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("QualificationWorks", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudentDiplomaData.ElectronicComponentsChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasExplanatoryNoteDoc")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasExplanatoryNotePdf")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPlagiarismReportPdf")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPresentationPpt")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRegulatoryControl")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasReviewDoc")
                        .HasColumnType("boolean");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("ElectronicComponentsChecklists", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudentDiplomaData.PhysicalComponentsChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasCircular")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCopyOfBankReceipt")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasExplanatoryNote")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGradeBook")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSignedReview")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasStudentCard")
                        .HasColumnType("boolean");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("PhysicalComponentsChecklists", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudentDiplomaData.QualificationWorkCharacteristics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasRealProjects")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplexDepartmental")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplexInterdepartmental")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplexInteruniversity")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplexProjectParticipant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefendedAtEnterprise")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEcoFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnterpriseOrdered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecommendedForImplementation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecommendedForMaster")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResearchBased")
                        .HasColumnType("boolean");

                    b.Property<int>("QualificationWorkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QualificationWorkId")
                        .IsUnique();

                    b.ToTable("QualificationWorkCharacteristics", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Departments", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Groups", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Secretary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Secretaries", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Specialties", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.AcademicDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AcademicDegrees", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("DecMembers", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecToMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DecMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("DiplomaExaminationCommissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaExaminationCommissionId");

                    b.HasIndex("DecMemberId", "DiplomaExaminationCommissionId")
                        .IsUnique();

                    b.ToTable("DecToMembers", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("DiplomaExaminationCommissions", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicDegreeId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademicDegreeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Teachers", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.Archive", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", "DiplomaExaminationCommission")
                        .WithOne("Archive")
                        .HasForeignKey("Core.Domain.Entities.ArchiveGroup.Archive", "DiplomaExaminationCommissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiplomaExaminationCommission");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.Defence", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", "DiplomaExaminationCommission")
                        .WithMany("Defences")
                        .HasForeignKey("DiplomaExaminationCommissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.ArchiveGroup.QualificationWork", "QualificationWork")
                        .WithOne("Defence")
                        .HasForeignKey("Core.Domain.Entities.ArchiveGroup.Defence", "QualificationWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiplomaExaminationCommission");

                    b.Navigation("QualificationWork");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.QualificationWork", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.Teacher", "Reviewer")
                        .WithMany("ReviewedQualificationWorks")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.StudyGroup.Student", "Student")
                        .WithOne("QualificationWork")
                        .HasForeignKey("Core.Domain.Entities.ArchiveGroup.QualificationWork", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.TeacherStaff.Teacher", "Teacher")
                        .WithMany("QualificationWorks")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Reviewer");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudentDiplomaData.ElectronicComponentsChecklist", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Student", "Student")
                        .WithOne("ElectronicComponentsChecklist")
                        .HasForeignKey("Core.Domain.Entities.StudentDiplomaData.ElectronicComponentsChecklist", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudentDiplomaData.PhysicalComponentsChecklist", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Student", "Student")
                        .WithOne("PhysicalComponentsChecklist")
                        .HasForeignKey("Core.Domain.Entities.StudentDiplomaData.PhysicalComponentsChecklist", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudentDiplomaData.QualificationWorkCharacteristics", b =>
                {
                    b.HasOne("Core.Domain.Entities.ArchiveGroup.QualificationWork", "QualificationWork")
                        .WithOne("QualificationWorkCharacteristics")
                        .HasForeignKey("Core.Domain.Entities.StudentDiplomaData.QualificationWorkCharacteristics", "QualificationWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QualificationWork");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Group", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Specialty", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Secretary", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Specialty", "Specialty")
                        .WithMany("Secretaries")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Specialty", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Department", "Department")
                        .WithMany("Specialties")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Student", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecMember", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.Teacher", "Teacher")
                        .WithMany("DecMembers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecToMember", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.DecMember", "DecMember")
                        .WithMany("DecToMembers")
                        .HasForeignKey("DecMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", "DiplomaExaminationCommission")
                        .WithMany("DecToMembers")
                        .HasForeignKey("DiplomaExaminationCommissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecMember");

                    b.Navigation("DiplomaExaminationCommission");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Group", "Group")
                        .WithOne("DiplomaExaminationCommission")
                        .HasForeignKey("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", "GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.Teacher", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.AcademicDegree", "AcademicDegree")
                        .WithMany("Teachers")
                        .HasForeignKey("AcademicDegreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.StudyGroup.Specialty", "Specialty")
                        .WithMany("Teachers")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicDegree");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.QualificationWork", b =>
                {
                    b.Navigation("Defence");

                    b.Navigation("QualificationWorkCharacteristics");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Department", b =>
                {
                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Group", b =>
                {
                    b.Navigation("DiplomaExaminationCommission");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Specialty", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Secretaries");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Student", b =>
                {
                    b.Navigation("ElectronicComponentsChecklist");

                    b.Navigation("PhysicalComponentsChecklist");

                    b.Navigation("QualificationWork");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.AcademicDegree", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecMember", b =>
                {
                    b.Navigation("DecToMembers");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", b =>
                {
                    b.Navigation("Archive");

                    b.Navigation("DecToMembers");

                    b.Navigation("Defences");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.Teacher", b =>
                {
                    b.Navigation("DecMembers");

                    b.Navigation("QualificationWorks");

                    b.Navigation("ReviewedQualificationWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
