// <auto-generated />
using System;
using DocumentGenerationSubsystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocumentGenerationSubsystem.Infrastructure.Migrations
{
    [DbContext(typeof(DbDocGenContext))]
    partial class DbDocGenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diploma")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DiplomaExaminationCommissionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProtocolRange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalPages")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaExaminationCommissionId")
                        .IsUnique();

                    b.ToTable("Archives", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.Defence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DefenceDate")
                        .HasColumnType("date");

                    b.Property<int>("DiplomaExaminationCommissionId")
                        .HasColumnType("integer");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("QualificationWorkId")
                        .HasColumnType("integer");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaExaminationCommissionId");

                    b.HasIndex("QualificationWorkId")
                        .IsUnique();

                    b.ToTable("Defences", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.QualificationWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionScore")
                        .HasColumnType("integer");

                    b.Property<string>("EctsGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagesCount")
                        .HasColumnType("integer");

                    b.Property<float>("PlagiarismPercent")
                        .HasColumnType("real");

                    b.Property<int>("ReviewerScore")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SupervisorScore")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("UniquePercent")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("QualificationWorks", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Departments", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Groups", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Specialties", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.AcademicDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AcademicDegrees", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("DecMembers", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecToMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DecMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("DiplomaExaminationCommissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaExaminationCommissionId");

                    b.HasIndex("DecMemberId", "DiplomaExaminationCommissionId")
                        .IsUnique();

                    b.ToTable("DecToMembers", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("DiplomaExaminationCommissions", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicDegreeId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AcademicDegreeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers", "diploma");
                });

            modelBuilder.Entity("DocumentGenerationSubsystem.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("WordTemplate")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("DocumentTemplates", "diploma");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.Archive", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", "DiplomaExaminationCommission")
                        .WithOne("Archive")
                        .HasForeignKey("Core.Domain.Entities.ArchiveGroup.Archive", "DiplomaExaminationCommissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiplomaExaminationCommission");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.Defence", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", "DiplomaExaminationCommission")
                        .WithMany("Defences")
                        .HasForeignKey("DiplomaExaminationCommissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.ArchiveGroup.QualificationWork", "QualificationWork")
                        .WithOne("Defence")
                        .HasForeignKey("Core.Domain.Entities.ArchiveGroup.Defence", "QualificationWorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiplomaExaminationCommission");

                    b.Navigation("QualificationWork");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.QualificationWork", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Student", "Student")
                        .WithOne("QualificationWork")
                        .HasForeignKey("Core.Domain.Entities.ArchiveGroup.QualificationWork", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.TeacherStaff.Teacher", "Teacher")
                        .WithMany("QualificationWorks")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Group", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Specialty", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Specialty", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Department", "Department")
                        .WithMany("Specialties")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Student", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecMember", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.Teacher", "Teacher")
                        .WithMany("DecMembers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecToMember", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.DecMember", "DecMember")
                        .WithMany("DecToMembers")
                        .HasForeignKey("DecMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", "DiplomaExaminationCommission")
                        .WithMany("DecToMembers")
                        .HasForeignKey("DiplomaExaminationCommissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecMember");

                    b.Navigation("DiplomaExaminationCommission");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", b =>
                {
                    b.HasOne("Core.Domain.Entities.StudyGroup.Group", "Group")
                        .WithOne("DiplomaExaminationCommission")
                        .HasForeignKey("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", "GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.Teacher", b =>
                {
                    b.HasOne("Core.Domain.Entities.TeacherStaff.AcademicDegree", "AcademicDegree")
                        .WithMany("Teachers")
                        .HasForeignKey("AcademicDegreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.StudyGroup.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicDegree");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Core.Domain.Entities.ArchiveGroup.QualificationWork", b =>
                {
                    b.Navigation("Defence");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Department", b =>
                {
                    b.Navigation("Specialties");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Group", b =>
                {
                    b.Navigation("DiplomaExaminationCommission");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Specialty", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Core.Domain.Entities.StudyGroup.Student", b =>
                {
                    b.Navigation("QualificationWork");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.AcademicDegree", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DecMember", b =>
                {
                    b.Navigation("DecToMembers");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.DiplomaExaminationCommission", b =>
                {
                    b.Navigation("Archive");

                    b.Navigation("DecToMembers");

                    b.Navigation("Defences");
                });

            modelBuilder.Entity("Core.Domain.Entities.TeacherStaff.Teacher", b =>
                {
                    b.Navigation("DecMembers");

                    b.Navigation("QualificationWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
